development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: universidade
  host: localhost
  pool: 5
  username: admin
  password: root
production:
  adapter: postgresql
  encoding: SQL_ASCII
  database: universidade
  host: localhost
  pool: 5
  username: admin
  password: root

